preload = ~/Pictures/Wallpapers/wallpaper.png
wallpaper = , ~/Pictures/Wallpapers/wallpaper.png

# Alternatively, you can use multiple wallpapers per monitor:
# preload = ~/Pictures/Wallpapers/monitor1.jpg
# preload = ~/Pictures/Wallpapers/monitor2.jpg
# wallpaper = DP-1, ~/Pictures/Wallpapers/monitor1.jpg
# wallpaper = HDMI-A-1, ~/Pictures/Wallpapers/monitor2.jpg

splash = false
